apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "manager.fullname" . }}
spec:
  dnsNames:
  - {{ include "manager.fullname" . }}-webhook.{{ .Release.Namespace }}.svc
  - {{ include "manager.fullname" . }}-webhook.{{ .Release.Namespace }}.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: {{ include "manager.fullname" . }}
  secretName: {{ include "manager.fullname" . }}-secret