apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ include "manager.fullname" . }}
  name: {{ include "manager.fullname" . }}-mutating
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: {{ include "manager.fullname" . }}-webhook
      namespace: {{ .Release.Namespace }}
      path: /mutate-rocket-hextech-io-v1alpha1-application
      port: 443
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: mapplication.kb.io
  reinvocationPolicy: Never
  rules:
  - apiGroups:
    - rocket.hextech.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - applications
  sideEffects: None
  timeoutSeconds: 10