apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ include "manager.fullname" . }}
  name: {{ include "manager.fullname" . }}-validating
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: {{ include "manager.fullname" . }}-webhook
      namespace: {{ .Release.Namespace }}
      path: /validate-rocket-hextech-io-v1alpha1-application
      port: 443
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: vapplication.kb.io
  rules:
  - apiGroups:
    - rocket.hextech.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - applications
  sideEffects: None
  timeoutSeconds: 10
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: {{ include "manager.fullname" . }}-webhook
      namespace: {{ .Release.Namespace }}
      path: /validate-rocket-hextech-io-v1alpha1-template
      port: 443
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: vtemplate.kb.io
  rules:
  - apiGroups:
    - rocket.hextech.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - templates
  sideEffects: None
  timeoutSeconds: 10
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: {{ include "manager.fullname" . }}-webhook
      namespace: {{ .Release.Namespace }}
      path: /validate-rocket-hextech-io-v1alpha1-distribution
      port: 443
  failurePolicy: Fail
  name: vdistribution.kb.io
  rules:
  - apiGroups:
    - rocket.hextech.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - distributions
  sideEffects: None