apiVersion: v1
kind: Service
metadata:
  name: {{ include "manager.fullname" . }}-webhook
  labels:
    {{- include "manager.labels" . | nindent 4 }}
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 9443
  selector:
    {{- include "manager.selectorLabels" . | nindent 4 }}
  type: ClusterIP