/*
Copyright 2023.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	time "time"

	rocketv1alpha1 "github.com/hex-techs/rocket/api/v1alpha1"
	versioned "github.com/hex-techs/rocket/client/clientset/versioned"
	internalinterfaces "github.com/hex-techs/rocket/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/hex-techs/rocket/client/listers/rocket/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// DistributionInformer provides access to a shared informer and lister for
// Distributions.
type DistributionInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.DistributionLister
}

type distributionInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewDistributionInformer constructs a new informer for Distribution type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewDistributionInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredDistributionInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredDistributionInformer constructs a new informer for Distribution type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredDistributionInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.RocketV1alpha1().Distributions(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.RocketV1alpha1().Distributions(namespace).Watch(context.TODO(), options)
			},
		},
		&rocketv1alpha1.Distribution{},
		resyncPeriod,
		indexers,
	)
}

func (f *distributionInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredDistributionInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *distributionInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&rocketv1alpha1.Distribution{}, f.defaultInformer)
}

func (f *distributionInformer) Lister() v1alpha1.DistributionLister {
	return v1alpha1.NewDistributionLister(f.Informer().GetIndexer())
}
