apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: rocket:scheduler
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: rocket:scheduler
subjects:
- kind: ServiceAccount
  name: {{ include "scheduler.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}