apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rocket:scheduler
rules:
- apiGroups:
  - apps
  resources:
  - controllerrevisions
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - rocket.hextech.io
  resources:
  - clusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - rocket.hextech.io
  resources:
  - workloads
  verbs:
  - get
  - list
  - watch
  - update
- apiGroups:
  - rocket.hextech.io
  resources:
  - workloads/status
  verbs:
  - list
  - watch
  - get
  - patch
  - update