---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - liuer.yangshipin.com
  resources:
  - Schedulers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - liuer.yangshipin.com
  resources:
  - Schedulers/finalizers
  verbs:
  - update
- apiGroups:
  - liuer.yangshipin.com
  resources:
  - Schedulers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - rocket.hextech.io
  resources:
  - applications
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rocket.hextech.io
  resources:
  - applications/finalizers
  verbs:
  - update
- apiGroups:
  - rocket.hextech.io
  resources:
  - applications/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - rocket.hextech.io
  resources:
  - clusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rocket.hextech.io
  resources:
  - clusters/finalizers
  verbs:
  - update
- apiGroups:
  - rocket.hextech.io
  resources:
  - clusters/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - rocket.hextech.io
  resources:
  - distributions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rocket.hextech.io
  resources:
  - distributions/finalizers
  verbs:
  - update
- apiGroups:
  - rocket.hextech.io
  resources:
  - distributions/status
  verbs:
  - get
  - patch
  - update
