---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - rocket.hextech.io
  resources:
  - applications
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rocket.hextech.io
  resources:
  - applications/finalizers
  verbs:
  - update
- apiGroups:
  - rocket.hextech.io
  resources:
  - applications/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - rocket.hextech.io
  resources:
  - clusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rocket.hextech.io
  resources:
  - clusters/finalizers
  verbs:
  - update
- apiGroups:
  - rocket.hextech.io
  resources:
  - clusters/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - rocket.hextech.io
  resources:
  - templates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rocket.hextech.io
  resources:
  - templates/finalizers
  verbs:
  - update
- apiGroups:
  - rocket.hextech.io
  resources:
  - templates/status
  verbs:
  - get
  - patch
  - update
