/*
Copyright 2023.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/hex-techs/rocket/api/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeDistributions implements DistributionInterface
type FakeDistributions struct {
	Fake *FakeRocketV1alpha1
	ns   string
}

var distributionsResource = schema.GroupVersionResource{Group: "rocket", Version: "v1alpha1", Resource: "distributions"}

var distributionsKind = schema.GroupVersionKind{Group: "rocket", Version: "v1alpha1", Kind: "Distribution"}

// Get takes name of the distribution, and returns the corresponding distribution object, and an error if there is any.
func (c *FakeDistributions) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.Distribution, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(distributionsResource, c.ns, name), &v1alpha1.Distribution{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Distribution), err
}

// List takes label and field selectors, and returns the list of Distributions that match those selectors.
func (c *FakeDistributions) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.DistributionList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(distributionsResource, distributionsKind, c.ns, opts), &v1alpha1.DistributionList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.DistributionList{ListMeta: obj.(*v1alpha1.DistributionList).ListMeta}
	for _, item := range obj.(*v1alpha1.DistributionList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested distributions.
func (c *FakeDistributions) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(distributionsResource, c.ns, opts))

}

// Create takes the representation of a distribution and creates it.  Returns the server's representation of the distribution, and an error, if there is any.
func (c *FakeDistributions) Create(ctx context.Context, distribution *v1alpha1.Distribution, opts v1.CreateOptions) (result *v1alpha1.Distribution, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(distributionsResource, c.ns, distribution), &v1alpha1.Distribution{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Distribution), err
}

// Update takes the representation of a distribution and updates it. Returns the server's representation of the distribution, and an error, if there is any.
func (c *FakeDistributions) Update(ctx context.Context, distribution *v1alpha1.Distribution, opts v1.UpdateOptions) (result *v1alpha1.Distribution, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(distributionsResource, c.ns, distribution), &v1alpha1.Distribution{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Distribution), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeDistributions) UpdateStatus(ctx context.Context, distribution *v1alpha1.Distribution, opts v1.UpdateOptions) (*v1alpha1.Distribution, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(distributionsResource, "status", c.ns, distribution), &v1alpha1.Distribution{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Distribution), err
}

// Delete takes name of the distribution and deletes it. Returns an error if one occurs.
func (c *FakeDistributions) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(distributionsResource, c.ns, name, opts), &v1alpha1.Distribution{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeDistributions) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(distributionsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.DistributionList{})
	return err
}

// Patch applies the patch and returns the patched distribution.
func (c *FakeDistributions) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.Distribution, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(distributionsResource, c.ns, name, pt, data, subresources...), &v1alpha1.Distribution{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Distribution), err
}
