apiVersion: rocket.hextech.io/v1alpha1
kind: Application
metadata:
  name: test
spec:
  regions:
    - beijing
  cloudArea: public
  environment: test
  replicas: 2
  template:
    apiVersion: apps/v1
    kind: Deployment
    spec:
      selector:
        matchLabels:
          app: nginx
      template:
        metadata:
          labels:
            app: nginx
        spec:
          containers:
          - name: nginx
            image: nginx:1.14.2
            ports:
            - containerPort: 80

